#!/bin/sh -e

export PREFIX=""
VENV_DIR=""

if [ -d 'venv' ] ; then
    VENV_DIR='venv'
elif [ -d '.venv' ] ; then
    VENV_DIR='.venv'
fi

if [[ -n $VENV_DIR ]]; then
    export PREFIX="${VENV_DIR}/bin/"
fi

set -x

# PYTHONPATH=. ${PREFIX}pytest --ignore ${VENV_DIR} --ignore apistar/layouts --cov=apistar --cov=tests --cov-report=term-missing ${@}
PYTHONPATH=. ${PREFIX}pytest --ignore ${VENV_DIR} --ignore apistar/layouts ${@}
